### ISSUE TITLE
yarn run v1.9.4 throws errors

### ISSUE THREAD

**Issue by rajinib** [IBM/watson-discovery-news-alerting#51]
Hi,

I'm from Cloudant Support and have a case from the user. The following problem has reported by the user and need your help.

"I did add my ibmcloud login info in the .env file name: pass: for login

yarn run start-notifier
yarn run v1.9.4
$ yarn run build-notifier && ./node_modules/babel-cli/bin/babel-node.js ./notifier.js
$ ./node_modules/babel-cli/bin/babel-node.js ./src/buildNotifierDB.js
credentials.username: undefined
credentials.password: undefined
/Users/jeffswope/watson-discovery-news-alerting/app/node_modules/@cloudant/cloudant/cloudant.js:42
      throw err;
      ^

Error: Invalid URL
    at Cloudant (/Users/jeffswope/watson-discovery-news-alerting/app/node_modules/@cloudant/cloudant/cloudant.js:38:15)
    at getCloudantService (/Users/jeffswope/watson-discovery-news-alerting/app/src/bluemix/config.js:64:16)
    at Object.<anonymous> (/Users/jeffswope/watson-discovery-news-alerting/app/src/models/access.js:22:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/Users/jeffswope/watson-discovery-news-alerting/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jeffswope/watson-discovery-news-alerting/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/"

Thanks,
Cloudant Support

**Comment by rhagarty** [comment]
@rajinib - need some more details:

- is the user using the latest version of this repo? It was updated recently (~3 weeks ago) to work with IAM keys.
- can I assume that the user was able to run `yarn start` to run the main app? Or did they get the same error with the undefined credentials?
- undefined credentials means that the values in the `.env` were not found. Make sure the file exists, and that the needed key-values are not commented out.

**Comment by rhagarty** [comment]
Closing this due to lack of response
